create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
create table email (email_id bigint not null, body_as_html longtext, body_as_string longtext, email_address varchar(255) not null, image_attachment longblob, recipient varchar(255) not null, sender varchar(255) not null, subject varchar(255) not null, text_attachment longtext, primary key (email_id)) engine=InnoDB;
create table email_folder (folder_id bigint not null, folder_name varchar(255) not null, number_of_sub_folder integer, root_folder bit, primary key (folder_id)) engine=InnoDB;
create table uuidgenerator (next_val bigint) engine=InnoDB;
insert into uuidgenerator values ( 1 );
insert into uuidgenerator values ( 1 );
